apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: open-webui
  namespace: ai
spec:
  # renovate: HelmChart
  repo: https://helm.openwebui.com/
  chart: open-webui
  version: 15.2.0
  targetNamespace: ai
  timeout: 1h
  failurePolicy: abort
  valuesContent: |-
    # https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml
    ollama:
      enabled: false
    pipelines:
      enabled: false
    websocket:
      enabled: false
    image:
      useSlim: true
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      host: open-webui.fritz.box
    openaiBaseApiUrl: "http://pc02.fritz.box:13305/v1"
    extraEnvVars:
      # prevent any local model downloads from Hugging Face
      - name: OFFLINE_MODE
        value: "true"
      - name: HF_HUB_OFFLINE
        value: "1"
      # no timeout for model response
      - name: AIOHTTP_CLIENT_TIMEOUT
        value: ""
      # STT via OpenAI-compatible API
      - name: AUDIO_STT_ENGINE
        value: "openai"
      - name: AUDIO_STT_OPENAI_API_BASE_URL
        value: "http://pc02.fritz.box:13305/v1"
      - name: AUDIO_STT_OPENAI_API_KEY
        value: "none"
      # TTS via OpenAI-compatible API
      - name: AUDIO_TTS_ENGINE
        value: "openai"
      - name: AUDIO_TTS_OPENAI_API_BASE_URL
        value: "http://pc02.fritz.box:13305/v1"
      - name: AUDIO_TTS_OPENAI_API_KEY
        value: "none"
      # RAG embedding via OpenAI-compatible API
      - name: RAG_EMBEDDING_ENGINE
        value: "openai"
      - name: RAG_OPENAI_API_BASE_URL
        value: "http://pc02.fritz.box:13305/v1"
      - name: RAG_OPENAI_API_KEY
        value: "none"
      - name: RAG_SYSTEM_CONTEXT
        value: "True"
    copyAppData:
      # -- Open WebUI copy-app-data init container command (overrides default)
      command: ["sh"]
      args: ["-c", "echo \"copyAppData: skipped\""]
