---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  cron: "0 12 * * SUN"
  task: "backup"
  groups:
  - default
  retain: 52
  concurrency: 2
  labels:
    schedule: 'weekly'
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-daily
  namespace: longhorn-system
spec:
  cron: "0 0 * * *"
  task: "snapshot"
  groups:
  - default
  retain: 7
  concurrency: 2
  labels:
    schedule: 'daily'