# dnsmasq as DNS server for local network
# Exposed on 192.168.178.2:53 via MetalLB
# Adds a few additional hostnames (homeassistant, k3s) and otherwise forwards to fritzbox.
# Configuration via config map. Depends on static IPs for hosts used as k8s nodes.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dnsmasq
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      containers:
        - name: dnsmasq
          image: ghcr.io/stephanme/dnsmasq
          imagePullPolicy: IfNotPresent
          command:
            - /bin/dnsmasq
            - --keep-in-foreground
            # - --no-daemon
            - --log-facility=- # log to stderr
            - --log-queries
            - --conf-file=/config/dnsmasq.conf
          ports:
            - containerPort: 1053
              protocol: UDP
            - containerPort: 1053
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 1053
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 1053
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /config/
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: dnsmasq-config
---
# Note: need to recreate LB when ports/protocols are changed
apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-service
  namespace: kube-system
  annotations:
    metallb.io/address-pool: dnsmasq-pool
    metallb.io/loadBalancerIPs: 192.168.178.2
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  ports:
    - name: udp
      port: 53
      protocol: UDP
      targetPort: 1053
    - name: tcp
      port: 53
      protocol: TCP
      targetPort: 1053
  selector:
    app: dnsmasq
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dnsmasq-pool
  namespace: kube-system
spec:
  addresses:
    - 192.168.178.2-192.168.178.2
  autoAssign: false