# dnsmasq as DNS server for local network
# Exposed on 192.168.178.2:53 via MetalLB
# Adds a few additional hostnames (homeassistant, k3s) and otherwise forwards to fritzbox.
# Configuration via config map. Depends on static IPs for hosts used as k8s nodes.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dnsmasq
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      containers:
        - name: dnsmasq
          image: ricardbejarano/dnsmasq:2.89
          imagePullPolicy: IfNotPresent
          command:
            - /bin/dnsmasq
            - --keep-in-foreground
            # - --no-daemon
            # - --log-queries
            - --conf-file=/config/dnsmasq.conf
          ports:
            - containerPort: 1053
              protocol: UDP
            - containerPort: 1053
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config/
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: dnsmasq-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-config
  namespace: kube-system
data:
  dnsmasq.conf: |
    # Configuration file for dnsmasq.
    #
    # Format is one option per line, legal options are the same
    # as the long options legal on the command line. See
    # "/usr/sbin/dnsmasq --help" or "man 8 dnsmasq" for details.
    # https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=blob;f=dnsmasq.conf.example;hb=HEAD
    port=1053
    no-resolv
    no-hosts
    domain=fritz.box
    expand-hosts
    cache-size=1500

    # forward to fritzbox DNS
    server=192.168.178.1

    address=/homeassistant.fritz.box/192.168.178.10
    address=/k3s.fritz.box/192.168.178.10
    address=/k3s.fritz.box/192.168.178.11
---
# Note: need to recreate LB when ports/protocols are changed
apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-service
  namespace: kube-system
  annotations:
    metallb.universe.tf/address-pool: dnsmasq-pool
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Local
  ports:
    - name: udp
      port: 53
      protocol: UDP
      targetPort: 1053
    - name: tcp
      port: 53
      protocol: TCP
      targetPort: 1053
  selector:
    app: dnsmasq
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dnsmasq-pool
  namespace: kube-system
spec:
  addresses:
  - 192.168.178.2-192.168.178.2