# pre-fetch images on all nodes
apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-images-nasbox
  namespace: zot
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: zot
          image: ghcr.io/project-zot/zot
          args:
          - "-v"
      nodeSelector:
        kubernetes.io/hostname: nasbox
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-images-pi1
  namespace: zot
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: zot
          image: ghcr.io/project-zot/zot
          args:
          - "-v"
      nodeSelector:
        kubernetes.io/hostname: pi1
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-images-pi2
  namespace: zot
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: zot
          image: ghcr.io/project-zot/zot
          args:
          - "-v"
      nodeSelector:
        kubernetes.io/hostname: pi2
      restartPolicy: Never