# deploy as daemonset on every node
# expose via MetalLB on VIP and via hostPorts on every node
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      kind: DaemonSet
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
    service:
      enabled: true
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.178.230
      spec:
        allocateLoadBalancerNodePorts: false
        externalTrafficPolicy: Local
        internalTrafficPolicy: Local
    securityContext:
      capabilities:
        add:
          - NET_BIND_SERVICE
      runAsNonRoot: false
      runAsUser: 0
      runAsGroup: 0
    ports:
      web:
        port: 80
        expose: 
          default: true
        protocol: TCP
        hostPort: 80
      websecure:
        port: 443
        expose:
          default: true
        protocol: TCP
        hostPort: 443
        tls:
          enable: true
      mqtt:
        port: 1883
        expose:
          default: true
        hostPort: 1883
        protocol: TCP
    metrics:
      prometheus:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels: # k8s labels
            release: prometheus
          # prom labels
          honorLabels: true