---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant-deployment
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          # https://github.com/home-assistant/core/pkgs/container/home-assistant
          image: ghcr.io/home-assistant/home-assistant:2025.9.2
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: "/config"
              name: homeassistant-persistent-storage
          resources:
            requests:
              cpu: 100m
              memory: 1Gi

        # code-server add-on: https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/templates/addons/code-server
        - name: codeserver
          image: ghcr.io/coder/code-server:4.103.2
          securityContext:
            runAsUser: 0
          ports:
            - name: codeserver
              containerPort: 12321
              protocol: TCP
          workingDir: /data/config
          args:
            - --auth
            - none
            - --user-data-dir
            - /data/config/.vscode
            - --port
            - "12321"
            - --disable-telemetry
            - /data/config
          volumeMounts:
            - name: homeassistant-persistent-storage
              mountPath: /data/config
      # nodeSelector:
      #   kubernetes.io/hostname: nasbox
      volumes:
        - name: homeassistant-persistent-storage
          persistentVolumeClaim:
            claimName: homeassistant-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  type: ClusterIP
  selector:
    app: homeassistant
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-codeserver
  namespace: homeassistant
spec:
  type: ClusterIP
  selector:
    app: homeassistant
  ports:
    - name: codeserver
      protocol: TCP
      port: 12321
      targetPort: codeserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`homeassistant.fritz.box`)
    services:
    - name: homeassistant
      port: 8123
  - kind: Rule
    match: Host(`homeassistant.fritz.box`) && PathPrefix(`/codeserver/`)
    middlewares:
    - name: codeserver-stripprefix
    services:
    - name: homeassistant-codeserver
      port: 12321
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: codeserver-stripprefix
  namespace: homeassistant
spec:
  stripPrefix:
    prefixes:
      - /codeserver/
