---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  labels:
    app: mosquitto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          # https://hub.docker.com/_/eclipse-mosquitto
          image: eclipse-mosquitto:2.0.21
          ports:
            - containerPort: 1883
          volumeMounts:
            - mountPath: "/mosquitto/data"
              name: mosquitto-data
            - name: config
              mountPath: /mosquitto/config/
              readOnly: true
            - name: secrets
              mountPath: /mosquitto/secrets/
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: secrets
          secret:
            secretName: mosquitto-secrets
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous false
    password_file /mosquitto/secrets/password_file
    persistence true
    persistence_location /mosquitto/data
    autosave_interval 1800
    upgrade_outgoing_qos true
    log_timestamp_format %Y-%m-%dT%H:%M:%S
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: ClusterIP
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc
  labels:
    app: mosquitto
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/no-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10M
---
# see /k3s/traefik-config.yaml for mqtt entrypoint
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mosquitto
spec:
  entryPoints:
    - mqtt
  routes:
  - match: HostSNI(`*`)
    services:
    - name: mosquitto
      port: 1883
