---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:2.3.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Europe/Berlin
            - name: "ZIGBEE2MQTT_DATA"
              value: "/data"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: zigbee2mqtt-data
              mountPath: /data
            - name: zigbee2mqtt-config
              mountPath: /data/configuration.yaml
              subPath: configuration.yaml
              # readOnly: true - zigbee2mqtt fails with read-only config
            - name: zigbee2mqtt-secrets
              mountPath: /data/secrets.yaml
              subPath: secrets.yaml
              readOnly: true
            - name: zigbee2mqtt-udev
              mountPath: /run/udev
            - name: devusb
              mountPath: /dev/serial/by-id
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/custom-zigbee
                    operator: In
                    values:
                      - "true"
      volumes:
        - name: zigbee2mqtt-data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-pvc
        - name: zigbee2mqtt-udev
          hostPath:
            path: /run/udev
        - name: devusb
          hostPath:
            path: /dev/serial/by-id
        - name: zigbee2mqtt-config
          configMap:
            name: zigbee2mqtt-config
        - name: zigbee2mqtt-secrets
          secret:
            secretName: zigbee2mqtt-secrets
---
# !!! restart zigbee2mqtt on change !!!
apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
  labels:
    app: zigbee2mqtt
data:
  # https://github.com/Koenkk/zigbee2mqtt/blob/master/data/configuration.example.yaml
  configuration.yaml: |-
    version: 4
    permit_join: false
    # Home Assistant integration (MQTT discovery)
    homeassistant: 
      enabled: true
    availability: 
      enabled: true
    mqtt:
      base_topic: zigbee2mqtt
      server: mqtt://mosquitto.homeassistant.svc.cluster.local
      user: '!secrets.yaml mqttuser'
      password: '!secrets.yaml mqttpassword'
      version: 5
      include_device_information: true
    # Zigbee Adapter path
    serial:
      adapter: zstack
      port: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
    # Enable UI
    frontend:
      enabled: true
      port: 8080
    advanced:
      network_key: '!secrets.yaml network_key'
      pan_id: 0x6e7f
      ext_pan_id: [47, 231, 231, 232, 84, 28, 16, 76]
      log_level: info
      log_output:
      - console
      # - file

    ## Map devices to persistent /data directory
    devices: /data/devices.yaml
    groups: /data/groups.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  ports:
    - name: zigbee2mqtt
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: zigbee2mqtt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10M
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: zigbee2mqtt
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`homeassistant.fritz.box`) && PathPrefix(`/zigbee2mqtt/`) 
    middlewares:
    - name: zigbee2mqtt-stripprefix
    services:
    - name: zigbee2mqtt
      port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: zigbee2mqtt-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /zigbee2mqtt/
---
# Only needed for updating the zigbee firmware.
# https://github.com/git-developer/ti-cc-tool
#
# 1. delete any completed zigbee-firmware job
# 2. update FIRMWARE_URL
# 3. ./deploy.sh
# 4. stop zigbee2mqtt by scaling to 0
# 5. unsuspend this job (edit in k9s)
# 6. check logs that firmware update was successful
# 7. ./deploy.sh to start zigbee2mqtt
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: zigbee-firmware
  name: zigbee-firmware
spec:
  suspend: true
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: zigbee-firmware
    spec:
      containers:
        - name: ti-cc-tool
          image: ckware/ti-cc-tool
          securityContext:
            privileged: true
          env:
            - name: FIRMWARE_URL
              value: https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20221226.zip
          command:
            - /usr/local/bin/run
            - -ewv
            - -p
            - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
            - --bootloader-sonoff-usb
          volumeMounts:
            - name: devusb
              mountPath: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
      nodeSelector:
        kubernetes.io/hostname: nasbox
      volumes:
        - name: devusb
          hostPath:
            path: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
      restartPolicy: Never