---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopia
  namespace: kopia
  labels:
    app: kopia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kopia
  template:
    metadata:
      labels:
        app: kopia
    spec:
      nodeSelector:
        kubernetes.io/hostname: nasbox
      securityContext:
        # nasbox: id backup
        # uid=1001(backup) gid=1001(backup) groups=1001(backup)
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: kopia
          # https://github.com/kopia/kopia/blob/master/tools/docker/Dockerfile
          image: kopia/kopia:0.22.2
          args:
            - server
            - start
            - --disable-csrf-token-checks
            - --address=0.0.0.0:51515
            - --refresh-interval=168h # TODO: should not lead to spinning up disks too often, 0 leads to high CPU load
            - --server-username=kopia
            - --server-control-username=server-control
            - --tls-cert-file=/app/config/kopia.cert
            - --tls-key-file=/app/config/kopia.key
          env:
            - name: KOPIA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kopia-secrets
                  key: KOPIA_PASSWORD
            - name: KOPIA_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kopia-secrets
                  key: KOPIA_SERVER_PASSWORD
            - name: KOPIA_SERVER_CONTROL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kopia-secrets
                  key: KOPIA_SERVER_CONTROL_PASSWORD
          ports:
            - containerPort: 51515
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: logs
              mountPath: /app/logs
            - name: cache
              mountPath: /app/cache
            - name: backups
              mountPath: /srv/kopia/backup-repo
      volumes:
        - name: config
          secret:
            secretName: kopia-config
        - name: logs
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: backups
          hostPath:
              path: /srv/kopia/backup-repo
              type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: kopia
  namespace: kopia
spec:
  type: NodePort
  selector:
    app: kopia
  ports:
    - port: 51515
      targetPort: 51515
      nodePort: 31515
