apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: paperless-ngx
  namespace: paperless
spec:
  # renovate: HelmChart
  repo: https://charts.gabe565.com
  chart: paperless-ngx
  version: 0.18.0
  targetNamespace: paperless
  timeout: 1h
  failurePolicy: abort
  valuesContent: |-
    # https://github.com/gabe565/charts/blob/main/charts/paperless-ngx/values.yaml
    env:
      TZ: Europe/Berlin
      PAPERLESS_URL: http://paperless.fritz.box
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_ADMIN_USER:
        valueFrom:
          secretKeyRef:
            name: paperless-secrets
            key: PAPERLESS_ADMIN_USER
      PAPERLESS_ADMIN_PASSWORD:
          secretKeyRef:
            name: paperless-secrets
            key: PAPERLESS_ADMIN_PASSWORD
      PAPERLESS_SECRET_KEY:
          secretKeyRef:
            name: paperless-secrets
            key: PAPERLESS_SECRET_KEY
      PAPERLESS_CONSUMER_POLLING: 10 # inotify seems not working with samba
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: always
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg.paperless.svc.cluster.local:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika.paperless.svc.cluster.local:9998
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 10Gi
      consume:
        enabled: true
        existingClaim: pvc-smb-consume
      export:
        enabled: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-smb-consume
  namespace: paperless
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: nasbox.fritz.box/public#paperless#
    volumeAttributes:
      source: //nasbox.fritz.box/public
      subDir: paperless
    nodeStageSecretRef:
      name: smb-public-creds
      namespace: smb-csi-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  pvc-smb-consume
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName:  pv-smb-consume
  storageClassName: smb
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: paperless
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`paperless.fritz.box`)
    services:
    - name: paperless-ngx
      port: 8000
