apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zot

images:
# https://github.com/project-zot/zot/pkgs/container/zot
- name: ghcr.io/project-zot/zot
  newTag: v2.1.7 

labels:
  - pairs:
      app.kubernetes.io/name: zot
      app.kubernetes.io/instance: zot
    includeSelectors: true

configMapGenerator:
- name: zot-config
  files:
    - config.json

resources:
- secrets.yaml
- zot.yaml
- zot-grafana.yaml