apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvcontrol-deployment
spec:
  selector:
    matchLabels:
      app: pvcontrol
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pvcontrol
    spec:
      containers:
        - name: pvcontrol
          image: ghcr.io/stephanme/pv-control:latest
          command:
            - python
            - -m
            - pvcontrol
            - --meter
            - KostalMeter
            - --wallbox
            - GoeWallbox
            - --relay
            - RaspiPhaseRelay
            - --car
            - SkodaCar
            - --config
            - |-
              {
                "meter": {
                  "host": "scb.fritz.box",
                  "port": 1502,
                  "unit_id": 71
                },
                "wallbox": {
                  "url": "http://go-echarger.fritz.box"
                },
                "relay": {
                  "enable_phase_switching": true,
                  "installed_on_host": "pi1",
                  "phase_relay_type": "NO"
                },
                "controller": {
                  "enable_auto_phase_switching": false,
                  "pv_allow_charging_delay": 300
                },
                "car": {
                  "disabled": false,
                  "user": "$(car_user)",
                  "password": "$(car_password)",
                  "vin": "$(car_vin)"
                }
              }
            - --hostname
            - $(node_name)
          env:
            - name: car_user
              valueFrom:
                secretKeyRef:
                  name: pvcontrol
                  key: car_user
            - name: car_password
              valueFrom:
                secretKeyRef:
                  name: pvcontrol
                  key: car_password
            - name: car_vin
              valueFrom:
                secretKeyRef:
                  name: pvcontrol
                  key: car_vin
            - name: node_name
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName              
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
          lifecycle:
            preStop:
              exec:
                # SIGINT needed for flask dev server, kill is a bash built-in
                command: ["bash", "-c", "kill -s SIGINT 1"]
      # prefer pi1 - needs descheduler migrate pvcontrol to pi1 after a pi1 downtime
      affinity:
        nodeAffinity:      
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - pi1

---
apiVersion: v1
kind: Service
metadata:
  name: pvcontrol-service
  labels:
    app: pvcontrol
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: tcp
  selector:
    app: pvcontrol
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pvcontrol-ingress
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`pvcontrol.fritz.box`)
    middlewares:
    - name: pvcontrol-compress
    services:
    - name: pvcontrol-service
      port: 8080
  # deprecated -> redirect
  - kind: Rule
    match: Path(`/pvcontrol`) || PathPrefix(`/pvcontrol/`)
    middlewares:
    - name: pvcontrol-redirect
    services:
    - name: pvcontrol-service
      port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pvcontrol-redirect
spec:
  redirectRegex:
    regex: .*
    replacement: http://pvcontrol.fritz.box
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pvcontrol-compress
spec:
  compress:
    minResponseBodyBytes: 2048
    excludedContentTypes:
      - font/woff2
      - font/woff
      - image/jpeg
      - image/png
      - image/vnd.microsoft.icon
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: pvcontrol
spec:
  endpoints:
  - path: /metrics
    port: tcp
  selector:
    matchLabels:
      app: pvcontrol
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
  name: pvcontrol
spec:
  groups:
  - name: pv-control.rules
    rules:
    - expr: max(pvcontrol_controller_total_charged_energy_wh_total) by (job)
      record: pvcontrol:total_charged_energy_wh_total
    - expr: max(pvcontrol_controller_charged_energy_wh_total) by (job, source)
      record: pvcontrol:charged_energy_wh_total
