{
 "title": "PV Control",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "max(pvcontrol_meter_power_consumption_total_watts) without (pod, instance)",
     "legendFormat": "Total"
    },
    {
     "expr": "max(pvcontrol_meter_power_consumption_total_watts-pvcontrol_wallbox_power_watts) without (pod, instance)",
     "legendFormat": "Home"
    },
    {
     "expr": "max(pvcontrol_wallbox_power_watts) without (pod, instance)",
     "legendFormat": "Car"
    }
   ]
  },
  {
   "title": "Power Sources",
   "type": "graph",
   "description": "Positive grid values = consume from grid; negative grid values = feeding into grid\n",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "max(pvcontrol_meter_power_watts) without(pod, instance)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Wallbox: Max Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "max(pvcontrol_wallbox_max_current_amperes) without (pod, instance)",
     "legendFormat": "Max Current"
    }
   ]
  },
  {
   "title": "Wallbox: Phases",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(pvcontrol_wallbox_phases_out) without (pod, instance)",
     "legendFormat": "# Phases (out)"
    },
    {
     "expr": "max(pvcontrol_wallbox_phases_in) without (pod, instance)",
     "legendFormat": "# Phases (in)"
    }
   ]
  },
  {
   "title": "Charge Mode",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(max_over_time(pvcontrol_controller_mode{pvcontrol_controller_mode=\"OFF\"}[$__interval]) == 1) * 1",
     "legendFormat": "Mode"
    },
    {
     "expr": "(max_over_time(pvcontrol_controller_mode{pvcontrol_controller_mode=\"PV_ONLY\"}[$__interval]) == 1) * 2",
     "legendFormat": "Mode"
    },
    {
     "expr": "(max_over_time(pvcontrol_controller_mode{pvcontrol_controller_mode=\"PV_ALL\"}[$__interval]) == 1) * 3",
     "legendFormat": "Mode"
    },
    {
     "expr": "(max_over_time(pvcontrol_controller_mode{pvcontrol_controller_mode=\"MAX\"}[$__interval]) == 1) * 4",
     "legendFormat": "Mode"
    },
    {
     "expr": "(max_over_time(pvcontrol_controller_mode{pvcontrol_controller_mode=\"MANUAL\"}[$__interval]) == 1) * 5",
     "legendFormat": "Mode"
    }
   ]
  }
 ]
}