---
# ServiceAccount for the USB backup watcher
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usb-backup-watcher
  namespace: kopia
---
# Role with permissions to manage Jobs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: usb-backup-watcher
  namespace: kopia
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get"]
---
# RoleBinding to grant permissions to ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: usb-backup-watcher
  namespace: kopia
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: usb-backup-watcher
subjects:
  - kind: ServiceAccount
    name: usb-backup-watcher
    namespace: kopia
---
# DaemonSet running the watcher on nasbox
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: usb-backup-watcher
  namespace: kopia
  labels:
    app: usb-backup-watcher
spec:
  selector:
    matchLabels:
      app: usb-backup-watcher
  template:
    metadata:
      labels:
        app: usb-backup-watcher
    spec:
      serviceAccountName: usb-backup-watcher
      nodeSelector:
        kubernetes.io/hostname: nasbox
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: watcher
          image: ghcr.io/stephanme/toolbox
          securityContext:
            allowPrivilegeEscalation: false
          command:
            - /bin/sh
            - /scripts/watcher.sh
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: media
              mountPath: /media
              readOnly: true
              mountPropagation: HostToContainer
            - name: scripts
              mountPath: /scripts
            - name: state
              mountPath: /state
      volumes:
        - name: media
          hostPath:
            path: /media
            type: Directory
        - name: scripts
          configMap:
            name: usb-backup-watcher-script
            defaultMode: 0755
        - name: state
          emptyDir: {}
