{
 "title": "Nibe Energy",
 "tags": [ "nibe" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "resolution", "label": "Resolution", "query": "5m,1h,1d,1w,1M" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Electric Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "increase(nibe_energy_meter_wh_total[$__range])",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(source:nibe_energy_meter_wh_total{source=\"pv\"}[$__range])",
     "legendFormat": "... PV"
    },
    {
     "expr": "increase(source:nibe_energy_meter_wh_total{source=\"grid\"}[$__range])",
     "legendFormat": "... Grid"
    }
   ]
  },
  {
   "title": "Electric Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "increase(nibe_energy_consumption_wh_total{mode=\"heating\"}[$__range])",
     "legendFormat": "Heating"
    },
    {
     "expr": "increase(nibe_energy_consumption_wh_total{mode=\"hotwater\"}[$__range])",
     "legendFormat": "Hot Water"
    },
    {
     "expr": "increase(nibe_energy_consumption_wh_total{mode=\"cooling\"}[$__range])",
     "legendFormat": "Cooling"
    },
    {
     "expr": "increase(nibe_energy_consumption_wh_total{mode=\"off\"}[$__range])",
     "legendFormat": "Off"
    }
   ]
  },
  {
   "title": "COP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "(increase(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr+add\"}[$__range]) + on (job) increase(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr+add\"}[$__range]) + on (job) increase(nibe_heat_meter_wh_total{sensor=\"EP14 cooling cpr\"}[$__range])) / on (job) increase(nibe_energy_meter_wh_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "COP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "increase(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr+add\"}[$__range]) / on (job) increase(nibe_energy_consumption_wh_total{mode=\"heating\"}[$__range])",
     "legendFormat": "Heating"
    },
    {
     "expr": "increase(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr+add\"}[$__range]) / on (job) increase(nibe_energy_consumption_wh_total{mode=\"hotwater\"}[$__range])",
     "legendFormat": "Hot Water"
    },
    {
     "expr": "increase(nibe_heat_meter_wh_total{sensor=\"EP14 cooling cpr\"}[$__range]) / on (job) increase(nibe_energy_consumption_wh_total{mode=\"cooling\"}[$__range])",
     "legendFormat": "Cooling"
    }
   ]
  },
  {
   "title": "Heat Meter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "increase(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr+add\"}[$__range]) + on (job) increase(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr+add\"}[$__range]) + on (job) increase(nibe_heat_meter_wh_total{sensor=\"EP14 cooling cpr\"}[$__range])",
     "legendFormat": "Overall"
    },
    {
     "expr": "round(increase(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr+add\"}[$__range]) + on (job) increase(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr+add\"}[$__range]) - on (job) increase(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr\"}[$__range]) - on (job) increase(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr\"}[$__range]), 1)",
     "legendFormat": "Add.Heat"
    }
   ]
  },
  {
   "title": "Heat Meter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "increase(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr+add\"}[$__range])",
     "legendFormat": "Heating"
    },
    {
     "expr": "increase(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr+add\"}[$__range])",
     "legendFormat": "Hot Water"
    },
    {
     "expr": "increase(nibe_heat_meter_wh_total{sensor=\"EP14 cooling cpr\"}[$__range])",
     "legendFormat": "Cooling"
    }
   ]
  },
  {
   "title": "Heat Meter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "max(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr+add\"}) - max(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr+add\"} offset $resolution)",
     "legendFormat": "Heating"
    },
    {
     "expr": "max(nibe_heat_meter_wh_total{sensor=\"EP14 cooling cpr\"}) - max(nibe_heat_meter_wh_total{sensor=\"EP14 cooling cpr\"} offset $resolution)",
     "legendFormat": "Cooling"
    },
    {
     "expr": "max(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr+add\"}) - max(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr+add\"} offset $resolution)",
     "legendFormat": "Hot Water"
    }
   ]
  },
  {
   "title": "Electric Energy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "increase(max(nibe_energy_meter_wh_total)[$resolution:])",
     "legendFormat": "Nibe"
    },
    {
     "expr": "increase(max(source:nibe_energy_meter_wh_total{source=\"grid\"})[$resolution:])",
     "legendFormat": "Grid"
    }
   ]
  },
  {
   "title": "Outdoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nibe_outdoor_temperature_celsius",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}