{
 "title": "Nibe Hot Water",
 "tags": [ "nibe" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Hot Water Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nibe_hotwater_temperature_celsius",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Heatpump Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rate(nibe_energy_meter_wh_total[10m])*3600",
     "legendFormat": "Heatpump Electric Power"
    },
    {
     "expr": "rate(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr+add\"}[10m])*3600",
     "legendFormat": "Heat Meter"
    }
   ]
  },
  {
   "title": "PV  Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "kpc_ac_power_total_watts", "legendFormat": "Total AC" }
   ]
  }
 ]
}