{
 "title": "Nibe Power",
 "tags": [ "nibe" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(rate(nibe_energy_meter_wh_total[5m])*3600) without (instance)",
     "legendFormat": "Total"
    },
    {
     "expr": "source:nibe_energy_meter_wh:rate{source=\"grid\"}*3600",
     "legendFormat": "Grid"
    },
    {
     "expr": "source:nibe_energy_meter_wh:rate{source=\"pv\"}*3600",
     "legendFormat": "PV"
    }
   ]
  },
  {
   "title": "Heatmeter Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(rate(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr+add\"}[10m])*3600) without (instance)",
     "legendFormat": "Heating"
    },
    {
     "expr": "sum(rate(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr+add\"}[10m])*3600) without (instance)",
     "legendFormat": "Hot Water"
    },
    {
     "expr": "sum(rate(nibe_heat_meter_wh_total{sensor=\"EP14 cooling cpr\"}[10m])*3600) without (instance)",
     "legendFormat": "Cooling"
    }
   ]
  },
  {
   "title": "Compressor Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(nibe_compressor_frequency_hertz) without (instance)",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "COP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(max(rate(nibe_heat_meter_wh_total{sensor=\"EP14 hotwater cpr+add\"}[10m])) + max(rate(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr+add\"}[10m])) + max(rate(nibe_heat_meter_wh_total{sensor=\"EP14 cooling cpr\"}[10m]))) / max(rate(nibe_energy_meter_wh_total[10m]))",
     "legendFormat": "COP"
    }
   ]
  },
  {
   "title": "Defrosting",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max(nibe_defrosting) without (instance)",
     "legendFormat": " "
    }
   ]
  }
 ]
}