{
 "title": "Nibe Heating",
 "tags": [ "nibe" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Degree Minutes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Degree Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "nibe_degree_minutes", "legendFormat": "Degree Minutes" }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Outdoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nibe_outdoor_temperature_celsius",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Indoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "z2m_temperature_celsius", "legendFormat": "{{sensor}}" }
   ]
  },
  { "title": "Heat Medium", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Heat Medium Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nibe_heat_medium_temperature_celsius",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Heat Medium Pump",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nibe_heat_medium_pump_speed_percent",
     "legendFormat": "Pump Speed {{sensor}}"
    },
    {
     "expr": "nibe_heat_medium_flow_liter_per_min",
     "legendFormat": "Flow"
    }
   ]
  },
  { "title": "Heat Pump", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Compressor Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nibe_compressor_frequency_hertz",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Heatpump Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rate(nibe_energy_meter_wh_total[10m])*3600",
     "legendFormat": "Heatpump Electric Power"
    },
    {
     "expr": "rate(nibe_heat_meter_wh_total{sensor=\"EP14 heating cpr+add\"}[10m])*3600",
     "legendFormat": "Heat Meter"
    }
   ]
  }
 ]
}