---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-sa-token
  namespace: kube-system
  labels:
    app.kubernetes.io/name: headlamp
  annotations:
    kubernetes.io/service-account.name: headlamp
type: kubernetes.io/service-account-token