apiVersion: batch/v1
kind: CronJob
metadata:
  name: regsync
  namespace: zot
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    spec:
      activeDeadlineSeconds: 14400  # 4h
      template:
        spec:
          containers:
            - name: regsync
              image: ghcr.io/stephanme/toolbox:latest
              command:
              - /bin/sh
              - -c
              - |
                set -e
                date
                regsynccmd=once  # check|once
                echo regsync ${regsynccmd}
                regsync ${regsynccmd} --config /etc/regsync/config.yaml --logopt json 2> >(tee -a /regsync.log >&2) || true
                FIXIDX=$(cat /regsync.log | grep -e '^{"time":' | jq -rs '[.[]|select(.msg=="Image sync needed" and (.target|test("/stephanme/")|not))|.target]|join(" ")')
                regctl registry set --tls=disabled registry.fritz.box
                echo "Fix missing index manifests"
                for target in $FIXIDX; do
                  set +e 
                  regctl manifest head $target >/dev/null 2>/dev/null
                  if [ $? -ne 0 ]; then
                    echo regctl index create $target --platform linux/amd64 --platform linux/arm64 --platform unknown/unknown --ref ${target:19}
                    if [ "$regsynccmd" = "once" ]; then
                      set -e
                      regctl index create $target --platform linux/amd64 --platform linux/arm64 --platform unknown/unknown --ref ${target:19}
                    fi
                  fi
                done
              volumeMounts:
                - mountPath: "/etc/regsync"
                  name: regsync-config
          restartPolicy: Never
          volumes:
            - name: regsync-config
              configMap:
                name: regsync-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: regsync-config
  namespace: zot
data:
  config.yaml: |-
    version: 1
    x-platforms: &x-platforms
      - linux/amd64
      - linux/arm64
      - unknown/unknown
    x-longhorn-main-tags: &x-longhorn-main-tags
      allow:
        - "v1\\.\\d+\\.\\d+"
      deny: # < v1.9.1
        - "v1\\.9\\.0"
        - "v1\\.[0-8]\\.\\d+"
    creds:
      - registry: registry.fritz.box
        tls: disabled
    defaults:
      ratelimit:
        min: 10
        retry: 15m
      parallel: 1
      fastCopy: true
    sync:
      # docker.io
      - source: eclipse-mosquitto
        target: registry.fritz.box/docker.io/library/eclipse-mosquitto
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "2\\.0\\.\\d+"
          deny: # < 2.0.22
            - "2\\.0\\.21"
            - "2\\.0\\.20"
            - "2\\.0\\.1\\d"
            - "2\\.0\\.\\d"
      - source: docker.io/grafana/grafana
        target: registry.fritz.box/docker.io/grafana/grafana
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "\\d\\d\\.\\d+\\.\\d+"
          deny: # < 12.1.0
            - "12\\.0\\.\\d+"
            - "1[01]\\.\\d+\\.\\d+"
      - source: docker.io/library/nginx
        target: registry.fritz.box/docker.io/library/nginx
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "1\\.\\d+\\.\\d+-alpine-slim"
          deny: # < 1.29.0-alpine-slim
            - "1\\.2[0-8]\\.\\d+-alpine-slim"
            - "1\\.1\\d\\.\\d+-alpine-slim"
            - "1\\.\\d\\.\\d+-alpine-slim"
      - source: koenkk/zigbee2mqtt
        target: registry.fritz.box/docker.io/koenkk/zigbee2mqtt
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "2\\.\\d+\\.\\d+"
          deny: # < 2.5.1
            - "2\\.5\\.0"
            - "2\\.[0-4]\\.\\d"
      - source: docker.io/longhornio/longhorn-engine
        target: registry.fritz.box/docker.io/longhornio/longhorn-engine
        type: repository
        platforms: *x-platforms
        tags: *x-longhorn-main-tags
      - source: docker.io/longhornio/longhorn-manager
        target: registry.fritz.box/docker.io/longhornio/longhorn-manager
        type: repository
        platforms: *x-platforms
        tags: *x-longhorn-main-tags
      - source: docker.io/longhornio/longhorn-ui
        target: registry.fritz.box/docker.io/longhornio/longhorn-ui
        type: repository
        platforms: *x-platforms
        tags: *x-longhorn-main-tags
      - source: docker.io/longhornio/longhorn-instance-manager
        target: registry.fritz.box/docker.io/longhornio/longhorn-instance-manager
        type: repository
        platforms: *x-platforms
        tags: *x-longhorn-main-tags
      - source: docker.io/longhornio/longhorn-share-manager
        target: registry.fritz.box/docker.io/longhornio/longhorn-share-manager
        type: repository
        platforms: *x-platforms
        tags: *x-longhorn-main-tags
      - source: docker.io/longhornio/backing-image-manager
        target: registry.fritz.box/docker.io/longhornio/backing-image-manager
        type: repository
        platforms: *x-platforms
        tags: *x-longhorn-main-tags
      - source: docker.io/longhornio/support-bundle-kit
        target: registry.fritz.box/docker.io/longhornio/support-bundle-kit
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v0\\.0\\.\\d+"
          deny: # < v0.0.61
            - "v0\\.0\\.60"
            - "v0\\.0\\.[1-5]\\d"
            - "v0\\.0\\.\\d"
      - source: docker.io/longhornio/csi-attacher
        target: registry.fritz.box/docker.io/longhornio/csi-attacher
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v4\\.\\d+\\.\\d+"
            - "v4\\.9\\.0-20250709"
          deny: # < v4.9.0-20250709
            - "v4\\.9\\.0"
            - "v4\\.[0-8]\\.\\d+"
      - source: docker.io/longhornio/csi-provisioner
        target: registry.fritz.box/docker.io/longhornio/csi-provisioner
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v5\\.\\d+\\.\\d+"
            - "v5\\.3\\.0-20250709"
          deny: # < v5.3.0-20250709
            - "v5\\.3\\.0"
            - "v5\\.[0-2]\\.\\d+"
      - source: docker.io/longhornio/csi-node-driver-registrar
        target: registry.fritz.box/docker.io/longhornio/csi-node-driver-registrar
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v2\\.\\d+\\.\\d+"
            - "v2\\.14\\.0-20250709"
          deny: # < v2.14.0-20250709
            - "v2\\.14\\.0"
            - "v2\\.1[0-3]\\.\\d+"
            - "v2\\.\\d\\.\\d+"
      - source: docker.io/longhornio/csi-resizer
        target: registry.fritz.box/docker.io/longhornio/csi-resizer
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v1\\.\\d+\\.\\d+"
            - "v1\\.14\\.0-20250709"
          deny: # < v1.14.0-20250709
            - "v1\\.14\\.0"
            - "v1\\.1[0-3]\\.\\d+"
            - "v1\\.\\d\\.\\d+"
      - source: docker.io/longhornio/csi-snapshotter
        target: registry.fritz.box/docker.io/longhornio/csi-snapshotter
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v8\\.\\d+\\.\\d+"
            - "v8\\.3\\.0-20250709"
          deny: # < v8.3.0-20250709
            - "v8\\.3\\.0"
            - "v8\\.[0-2]\\.\\d+"
      - source: docker.io/longhornio/livenessprobe
        target: registry.fritz.box/docker.io/longhornio/livenessprobe
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v2\\.\\d+\\.\\d+"
            - "v2\\.16\\.0-20250709"
          deny: # < v2.16.0-20250709
            - "v2\\.16\\.0"
            - "v2\\.1[0-5]\\.\\d+"
            - "v2\\.\\d\\.\\d+"
      # ghcr.io
      - source: ghcr.io/coder/code-server
        target: registry.fritz.box/ghcr.io/coder/code-server
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "4\\.1\\d\\d\\.\\d+"
          deny: # < 4.102.2
            - "4\\.102\\.[01]"
            - "4\\.10[01]\\.\\d+"
      - source: ghcr.io/hikhvar/mqtt2prometheus
        target: registry.fritz.box/ghcr.io/hikhvar/mqtt2prometheus
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v0\\.\\d+\\.\\d+"
          deny: # < v0.1.7
            - "v0\\.1\\.[0-6]"
            - "v0\\.0\\.\\d+"
      - source: ghcr.io/home-assistant/home-assistant
        target: registry.fritz.box/ghcr.io/home-assistant/home-assistant
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "2025\\.\\d+\\.\\d+"
          deny: # < 2025.7.3
            - "2025\\.7\\.[0-2]"
            - "2025\\.[1-6]\\.\\d+"
      - source: ghcr.io/stephanme/modbus_exporter
        target: registry.fritz.box/ghcr.io/stephanme/modbus_exporter
        type: repository
        tags:
          allow:
            - "latest"
            - "v\\d+"
          deny: # < v8
            - "v[0-7]"
      - source: ghcr.io/stephanme/pv-control
        target: registry.fritz.box/ghcr.io/stephanme/pv-control
        type: repository
        tags:
          allow:
            - "latest"
            - "v\\d+"
          deny: # < v13
            - "v1[0-3]"
            - "v\\d"
      - source: ghcr.io/stephanme/toolbox
        target: registry.fritz.box/ghcr.io/stephanme/toolbox
        type: repository
        tags:
          allow:
            - "latest"
            - "v\\d+"
          deny: # < v4
            - "v[0123]"
      - source: ghcr.io/project-zot/zot
        target: registry.fritz.box/ghcr.io/project-zot/zot
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v2\\.\\d+\\.\\d+"
          deny: # < v2.1.5
            - "v2\\.1\\.[0-5]"
            - "v2\\.0\\.\\d+"
      # quay.io
      - source: quay.io/kiwigrid/k8s-sidecar
        target: registry.fritz.box/quay.io/kiwigrid/k8s-sidecar
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "1\\.\\d+\\.\\d+"
          deny: # < 1.30.3
            - "1\\.30\\.[0-2]"
            - "1\\.[12]\\d\\.\\d+"
            - "1\\.\\d\\.\\d+"
      - source: quay.io/prometheus/alertmanager
        target: registry.fritz.box/quay.io/prometheus/alertmanager
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v0\\.\\d+\\.\\d+"
          deny: # < v0.28.1
            - "v0\\.28\\.0"
            - "v0\\.2[0-7]\\.\\d+"
            - "v0\\.1\\d\\.\\d+"
            - "v0\\.\\d\\.\\d+"
      - source: quay.io/prometheus/blackbox-exporter
        target: registry.fritz.box/quay.io/prometheus/blackbox-exporter
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v0\\.\\d+\\.\\d+"
          deny: # < v0.26.0
            - "v0\\.2[0-5]\\.\\d+"
            - "v0\\.1\\d\\.\\d+"
            - "v0\\.\\d\\.\\d+"
      - source: quay.io/prometheus/node-exporter
        target: registry.fritz.box/quay.io/prometheus/node-exporter
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v1\\.\\d+\\.\\d+"
          deny: # < v1.9.1
            - "v1\\.9\\.0"
            - "v1\\.[0-8]\\.\\d+"
      - source: quay.io/prometheus/prometheus
        target: registry.fritz.box/quay.io/prometheus/prometheus
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v3\\.\\d+\\.\\d+"
          deny: # < v3.5.0
            - "v3\\.[0-4]\\.\\d+"
      - source: quay.io/prometheus-operator/prometheus-config-reloader
        target: registry.fritz.box/quay.io/prometheus-operator/prometheus-config-reloader
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v0\\.\\d+\\.\\d+"
          deny: # < v0.83.0
            - "v0\\.8[0-2]\\.\\d+"
            - "v0\\.[1-7]\\d\\.\\d+"
            - "v0\\.\\d\\.\\d+"
      - source: quay.io/prometheus-operator/prometheus-operator
        target: registry.fritz.box/quay.io/prometheus-operator/prometheus-operator
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v0\\.\\d+\\.\\d+"
          deny: # < v0.83.0
            - "v0\\.8[0-2]\\.\\d+"
            - "v0\\.[1-7]\\d\\.\\d+"
            - "v0\\.\\d\\.\\d+"
      # registry.k8s.io
      - source: registry.k8s.io/kube-state-metrics/kube-state-metrics
        target: registry.fritz.box/registry.k8s.io/kube-state-metrics/kube-state-metrics
        type: repository
        platforms: *x-platforms
        tags:
          allow:
            - "v2\\.\\d+\\.\\d+"
          deny: # < v2.16.0
            - "v2\\.1[0-5]\\.\\d+"
            - "v2\\.\\d\\.\\d+"
