apiVersion: batch/v1
kind: CronJob
metadata:
  name: regsync
  namespace: zot
spec:
  schedule: "0 2 * * *"
  timeZone: Europe/Berlin
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    spec:
      activeDeadlineSeconds: 14400  # 4h
      template:
        spec:
          containers:
            - name: regsync
              image: ghcr.io/stephanme/toolbox:latest
              command:
              - /bin/sh
              - -c
              - |
                set -e
                date
                regsynccmd=once  # check|once
                echo regsync ${regsynccmd}
                regsync ${regsynccmd} --config /etc/regsync/config.yaml --logopt json 2> >(tee -a /regsync.log >&2) || true
                FIXIDX=$(cat /regsync.log | grep -e '^{"time":' | jq -rs '[.[]|select(.msg=="Image sync needed" and (.target|test("/stephanme|immich-server/")|not))|.target]|join(" ")')
                regctl registry set --tls=disabled registry.fritz.box
                echo "Fix missing index manifests"
                for target in $FIXIDX; do
                  set +e 
                  regctl manifest head $target >/dev/null 2>/dev/null
                  if [ $? -ne 0 ]; then
                    echo regctl index create $target --platform linux/amd64 --platform linux/arm64 --platform unknown/unknown --ref ${target:19}
                    if [ "$regsynccmd" = "once" ]; then
                      set -e
                      regctl index create $target --platform linux/amd64 --platform linux/arm64 --platform unknown/unknown --ref ${target:19}
                    fi
                  fi
                done
              volumeMounts:
                - mountPath: "/etc/regsync"
                  name: regsync-config
          restartPolicy: Never
          volumes:
            - name: regsync-config
              configMap:
                name: regsync-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: regsync-latest
  namespace: zot
spec:
  # Manual trigger only (runs only on Jan 1st at midnight)
  schedule: "0 0 1 1 *"
  timeZone: Europe/Berlin
  concurrencyPolicy: Replace
  suspend: true
  jobTemplate:
    spec:
      activeDeadlineSeconds: 14400  # 4h
      template:
        spec:
          containers:
            - name: regsync-latest
              image: ghcr.io/stephanme/toolbox:latest
              command:
              - /bin/sh
              - -c
              - |
                set -e
                date
                regsynccmd=once
                echo regsync ${regsynccmd}
                regsync ${regsynccmd} --config /etc/regsync/config-latest.yaml --logopt json || true
              volumeMounts:
                - mountPath: "/etc/regsync"
                  name: regsync-config-latest
          restartPolicy: Never
          volumes:
            - name: regsync-config-latest
              configMap:
                name: regsync-config-latest
