# pre-fetch images for stateful sets and recreate deployments to avoid longer downtimes
apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-images-nasbox
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant
          command:
          - /bin/sh
          - -c
          - echo home-assistant image available
        - name: codeserver
          image: ghcr.io/coder/code-server
          command:
          - /bin/sh
          - -c
          - echo code-server image available
      nodeSelector:
        kubernetes.io/hostname: nasbox
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-images-pi1
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant
          command:
          - /bin/sh
          - -c
          - echo home-assistant image available
        - name: codeserver
          image: ghcr.io/coder/code-server
          command:
          - /bin/sh
          - -c
          - echo code-server image available
      nodeSelector:
        kubernetes.io/hostname: pi1
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-images-pi2
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant
          command:
          - /bin/sh
          - -c
          - echo home-assistant image available
        - name: codeserver
          image: ghcr.io/coder/code-server
          command:
          - /bin/sh
          - -c
          - echo code-server image available
      nodeSelector:
        kubernetes.io/hostname: pi2
      restartPolicy: Never