apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: kube-prometheus-stack-alertmanagerconfig
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: alertmanagerconfig
spec:
  route:
    groupBy: ["job"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: email
    routes:
      - matchers:
        - matchType: "="
          name: alertname
          value: Watchdog
        receiver: "null"
      - matchers:
        - matchType: "="
          name: alertname
          value: InfoInhibitor
        receiver: "null"

  receivers:
    - name: "null"
    - name: email
      emailConfigs: # obfuscated email addresses (unicode escaped), secrets are not supported
        - to: "\u006d\u0065\u0072\u006b\u0065\u0072\u002e\u0073\u0074\u0065\u0070\u0068\u0061\u006e\u0040\u0067\u006d\u0061\u0069\u006c\u002e\u0063\u006f\u006d"
          sendResolved: true
          from: "\u006d\u006f\u006e\u0069\u0074\u006f\u0072\u0069\u006e\u0067\u002e\u0075\u0070\u0074\u0069\u006d\u0065\u0040\u0067\u006d\u0061\u0069\u006c\u002e\u0063\u006f\u006d"
          smarthost: smtp.gmail.com:587
          authUsername: "\u006d\u006f\u006e\u0069\u0074\u006f\u0072\u0069\u006e\u0067\u002e\u0075\u0070\u0074\u0069\u006d\u0065\u0040\u0067\u006d\u0061\u0069\u006c\u002e\u0063\u006f\u006d"
          authPassword: # https://support.google.com/mail/answer/185833?hl=en-GB
            name: kube-prometheus-stack
            key: smtp_auth_password

  # Inhibition rules allow to mute a set of alerts given that another alert is firing.
  inhibitRules:
    # mute any warning/info-level notifications if the same alert is already critical.
    - sourceMatch:
        - name: severity
          value: "critical"
      targetMatch:
        - matchType: "=~"
          name: severity
          value: "warning|info"
      equal: ["alertname", "namespace"]
    # mute any info-level notifications if the same alert is already a warning.
    - sourceMatch:
        - name: severity
          value: "warning"
      targetMatch:
        - name: severity
          value: "info"
      equal: ["alertname", "namespace"]
    # InfoInhibitor, https://runbooks.prometheus-operator.dev/runbooks/general/infoinhibitor/
    - sourceMatch:
        - name: alertname
          value: "InfoInhibitor"
      targetMatch:
        - name: severity
          value: "info"
      equal: ["namespace"]
