apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-operator-crds
  namespace: monitoring
spec:
  # renovate: HelmChart
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus-operator-crds
  version: 7.0.0
  targetNamespace: monitoring
  timeout: 10m
  failurePolicy: abort
