{
 "title": "PV Control",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max(pvcontrol_meter_power_consumption_total_watts) without (pod, instance)",
     "legendFormat": "Total"
    },
    {
     "expr": "max(pvcontrol_meter_power_consumption_total_watts-pvcontrol_wallbox_power_watts) without (pod, instance)",
     "legendFormat": "Home"
    },
    {
     "expr": "max(pvcontrol_wallbox_power_watts) without (pod, instance)",
     "legendFormat": "Car"
    }
   ]
  },
  {
   "title": "Power Sources",
   "type": "timeseries",
   "description": "Positive grid values = consume from grid; negative grid values = feeding into grid\n",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max(pvcontrol_meter_power_watts) without(pod, instance)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Wallbox: Max Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "max(pvcontrol_wallbox_max_current_amperes) without (pod, instance)",
     "legendFormat": "Max Current"
    }
   ]
  },
  {
   "title": "Wallbox: Phases",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(pvcontrol_wallbox_phases_out) without (pod, instance)",
     "legendFormat": "# Phases (out)"
    },
    {
     "expr": "max(pvcontrol_wallbox_phases_in) without (pod, instance)",
     "legendFormat": "# Phases (in)"
    }
   ]
  },
  {
   "title": "Charge Mode",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(pvcontrol_controller_mode{pvcontrol_controller_mode=\"OFF\"} == bool 1) + on (job) (pvcontrol_controller_mode{pvcontrol_controller_mode=\"PV_ONLY\"} == bool 1)*2 + on (job) (pvcontrol_controller_mode{pvcontrol_controller_mode=\"PV_ALL\"} == bool 1)*3 + on (job) (pvcontrol_controller_mode{pvcontrol_controller_mode=\"MAX\"} == bool 1)*4 + on (job) (pvcontrol_controller_mode{pvcontrol_controller_mode=\"MANUAL\"} == bool 1)*5",
     "legendFormat": "Mode"
    }
   ]
  }
 ]
}