apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvcontrol-deployment
spec:
  selector:
    matchLabels:
      app: pvcontrol
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pvcontrol
    spec:
      containers:
        - name: pvcontrol
          image: stephanme/pv-control:latest
          command:
            - python
            - -m
            - pvcontrol
            - --meter
            - KostalMeter
            - --wallbox
            - GoeWallbox
            - --car
            - VolkswagenIDCar
            - --config
            - |-
              {
                "meter": {
                  "host": "scb.fritz.box",
                  "port": 1502,
                  "unit_id": 71
                },
                "wallbox": {
                  "url": "http://go-echarger.fritz.box",
                  "phase_relay_type": "NO"
                },
                "controller": {
                  "enable_phase_switching": true,
                  "enable_auto_phase_switching": false,
                  "pv_allow_charging_delay": 300
                },
                "car": {
                  "disabled": false,
                  "user": "$(car_user)",
                  "password": "$(car_password)",
                  "vin": "$(car_vin)"
                }
              }
          env:
            - name: car_user
              valueFrom:
                secretKeyRef:
                  name: pvcontrol
                  key: car_user
            - name: car_password
              valueFrom:
                secretKeyRef:
                  name: pvcontrol
                  key: car_password
            - name: car_vin
              valueFrom:
                secretKeyRef:
                  name: pvcontrol
                  key: car_vin
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
          lifecycle:
            preStop:
              exec:
                # SIGINT needed for flask dev server, kill is a bash built-in
                command: ["bash", "-c", "kill -s SIGINT 1"]
      nodeSelector:
        kubernetes.io/hostname: pi1

---
apiVersion: v1
kind: Service
metadata:
  name: pvcontrol-service
  labels:
    app: pvcontrol
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: tcp
  selector:
    app: pvcontrol
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pvcontrol-ingress
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Path(`/pvcontrol`) || PathPrefix(`/pvcontrol/`)
    middlewares:
    - name: pvcontrol-stripprefix
    - name: pvcontrol-compress
    services:
    - name: pvcontrol-service
      port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pvcontrol-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /pvcontrol
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pvcontrol-compress
spec:
  compress:
    minResponseBodyBytes: 2048
    excludedContentTypes:
      - font/woff2
      - font/woff
      - image/jpeg
      - image/png
      - image/vnd.microsoft.icon