kind: Deployment
apiVersion: apps/v1
metadata:
  name: immich-server
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
  template:
    metadata:
      labels:
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server
          env:
            - name: IMMICH_PORT
              value: '2283'
            - name: TZ
              value: Europe/Berlin
            - name: IMMICH_TELEMETRY_INCLUDE
              value: all
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: host
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: dbname
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: password
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning:3003
          startupProbe:
            periodSeconds: 10
            failureThreshold: 60
            httpGet:
              port: http
              path: /api/server/ping
          livenessProbe:
            httpGet:
              port: http
              path: /api/server/ping
          readinessProbe:
            httpGet:
              port: http
              path: /api/server/ping
          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload
          ports:
            - name: http
              containerPort: 2283
            - name: server-metrics
              containerPort: 8081
            - name: jobs-metrics
              containerPort: 8082
      volumes:
        - name: library
          persistentVolumeClaim:
              claimName: immich-library
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 2283
      targetPort: http
    - name: server-metrics
      port: 8081
      targetPort: server-metrics
    - name: jobs-metrics
      port: 8082
      targetPort: jobs-metrics
  selector:
