# nginx deployment for homepage
# exposed via Traefik
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
  template:
    metadata:
      labels:
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: homepage-index
          mountPath: /usr/share/nginx/html
        - name: homepage-static-pages
          mountPath: /usr/share/nginx/html/homepage
      volumes:
      - name: homepage-index
        configMap:
          name: homepage-index
      - name: homepage-static-pages
        configMap:
          name: homepage-static-pages
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
spec:
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`k3s.fritz.box`) && (Path(`/`) || PathPrefix(`/homepage/`))
    services:
    - name: homepage
      port: 80
