apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

labels:
  - pairs:
      app.kubernetes.io/instance: immich-db
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: immich
    includeSelectors: true

resources:
- database.yaml