mqtt:
  # The MQTT broker to connect to, credentials go via env vars
  server: tcp://mosquitto.homeassistant.svc.cluster.local:1883
  client_id: shellypm2gen4-exporter
  # subscribe to mosquitto metrics
  topic_path: shellies2/+/status/cover:0
  # Optional: Regular expression to extract the device ID from the topic path. The default regular expression, assumes
  # that the last "element" of the topic_path is the device id.
  # The regular expression must contain a named capture group with the name deviceid
  # !! yaml and regexp escaping !!
  device_id_regex: "shellies2/(?P<deviceid>[^/]+)/.*"
  # The MQTT QoS level
  qos: 0
cache:
  # Timeout. Each received metric will be presented for this time if no update is send via MQTT.
  # Set the timeout to -1 to disable the deletion of metrics from the cache. The exporter presents the ingest timestamp
  # to prometheus.
  timeout: -1
# This is a list of valid metrics. Only metrics listed here will be exported
metrics:
  - prom_name: shelly_position
    mqtt_name: current_pos
    type: gauge
  - prom_name: shelly_power
    mqtt_name: apower
    type: gauge
  - prom_name: shelly_temperature
    mqtt_name: temperature.tC
    type: gauge
