mqtt:
  # The MQTT broker to connect to, credentials go via env vars
  server: tcp://mosquitto.homeassistant.svc.cluster.local:1883
  client_id: zigbee2mqtt-availability-exporter
  # subscribe to zigbee2mqtt availability topics
  topic_path: zigbee2mqtt/+/availability
  # Optional: Regular expression to extract the device ID from the topic path. The default regular expression, assumes
  # that the last "element" of the topic_path is the device id.
  # The regular expression must contain a named capture group with the name deviceid
  # !! yaml and regexp escaping !!
  device_id_regex: "zigbee2mqtt/(?P<deviceid>[^/]+)/.*"
  # The MQTT QoS level
  qos: 0
cache:
  # Timeout. Each received metric will be presented for this time if no update is send via MQTT.
  # Set the timeout to -1 to disable the deletion of metrics from the cache. The exporter presents the ingest timestamp
  # to prometheus.
  timeout: 24h
# This is a list of valid metrics. Only metrics listed here will be exported
metrics:
  - prom_name: z2m_online
    mqtt_name: state
    type: gauge
    omit_timestamp: true
    string_value_mapping:
      # A map of string to metric value.
      map:
        online: 1
        offline: 0
      # Metric value to use if a match cannot be found in the map above.
      # If not specified, parsing error will occur.
      error_value: 0
