{
 "title": "Kostal Energy",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "resolution", "label": "Resolution", "query": "5m,1h,1d,1w,1M" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overall Home Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "kpc_home_power_consumption_total_wh_total"
    }
   ]
  },
  {
   "title": "... from PV",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "kpc_home_power_consumption_wh_total{source=\"pv\"}"
    }
   ]
  },
  {
   "title": "... from Grid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "kpc_home_power_consumption_wh_total{source=\"grid\"}"
    }
   ]
  },
  {
   "title": "Overall Energy to Grid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "kpc_ac_energy_to_grid_wh_total" }
   ]
  },
  {
   "title": "Car",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "goe_energy_wh_total" }
   ]
  },
  {
   "title": "Home Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "expr": "kpc_home_power_consumption_total_wh_total - kpc_home_power_consumption_total_wh_total offset $resolution",
     "legendFormat": "Total"
    },
    {
     "expr": "kpc_home_power_consumption_wh_total{source!=\"battery\"} - kpc_home_power_consumption_wh_total{source!=\"battery\"} offset $resolution",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Energy to Grid",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "expr": "kpc_ac_energy_to_grid_wh_total - kpc_ac_energy_to_grid_wh_total offset $resolution",
     "legendFormat": "To Grid"
    }
   ]
  },
  {
   "title": "Car Charging",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "expr": "goe_energy_wh_total - goe_energy_wh_total offset $resolution",
     "legendFormat": "Car"
    }
   ]
  }
 ]
}