apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: zigbee-device
spec:
  rules:
    # /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
    # feature.node.kubernetes.io/usb-ff_10c4_ea60.present=true
    - name: sonoff-zigbee-device
      labels:
        feature.node.kubernetes.io/custom-zigbee: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ["ff"] }
            vendor: { op: In, value: ["10c4"] }
            device: { op: In, value: ["ea60"] }