{
 "title": "Kostal Power",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Powermeter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "kpc_powermeter_total_watts", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(kpc_home_power_consumption_watts)",
     "legendFormat": "Total"
    },
    {
     "expr": "kpc_home_power_consumption_watts{source!=\"battery\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "PV  Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "kpc_ac_power_total_watts", "legendFormat": "Total AC" },
    { "expr": "kpc_dc_power_total_watts", "legendFormat": "Total DC" },
    {
     "expr": "kpc_dc_power_watts{source!=\"DC3\"}\n",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}