{
 "title": "Kostal Energy",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "resolution", "label": "Resolution", "query": "5m,1h,1d,1w,1M" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "PV",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(increase(kpc_ac_energy_yield_wh_total[$__range]))"
    }
   ]
  },
  {
   "title": "Energy to Grid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(kpc_ac_energy_to_grid_wh_total@${__to:date:seconds}) - sum(kpc_ac_energy_to_grid_wh_total@${__from:date:seconds})"
    }
   ]
  },
  {
   "title": "Home Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(kpc_home_power_consumption_total_wh_total@${__to:date:seconds}) - sum(kpc_home_power_consumption_total_wh_total@${__from:date:seconds})"
    }
   ]
  },
  {
   "title": "... from PV",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(kpc_home_power_consumption_wh_total{source=\"pv\"}@${__to:date:seconds}) - sum(kpc_home_power_consumption_wh_total{source=\"pv\"}@${__from:date:seconds})",
     "legendFormat": "PV"
    }
   ]
  },
  {
   "title": "... from Grid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(kpc_home_power_consumption_wh_total{source=\"grid\"}@${__to:date:seconds}) - sum(kpc_home_power_consumption_wh_total{source=\"grid\"}@${__from:date:seconds})"
    }
   ]
  },
  {
   "title": "... to Nibe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(increase(nibe_energy_meter_wh_total[$__range]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(source:nibe_energy_meter_wh_total{source=\"pv\"}[$__range]))",
     "legendFormat": "... PV"
    },
    {
     "expr": "sum(increase(source:nibe_energy_meter_wh_total{source=\"grid\"}[$__range]))",
     "legendFormat": "... Grid"
    }
   ]
  },
  {
   "title": "... to Car",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(increase(goe_energy_wh_total[$__range]))"
    }
   ]
  },
  {
   "title": "... to Car",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pvcontrol:total_charged_energy_wh_total[$__range])",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(pvcontrol:charged_energy_wh_total{source=\"pv\"}[$__range])",
     "legendFormat": "... PV"
    },
    {
     "expr": "increase(pvcontrol:charged_energy_wh_total{source=\"grid\"}[$__range])",
     "legendFormat": "... Grid"
    }
   ]
  },
  {
   "title": "Home Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "max(kpc_home_power_consumption_total_wh_total) - max(kpc_home_power_consumption_total_wh_total offset $resolution)",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (source)(kpc_home_power_consumption_wh_total{source!=\"battery\"}) - max by (source)(kpc_home_power_consumption_wh_total{source!=\"battery\"} offset $resolution)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "PV",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "max(kpc_ac_energy_yield_wh_total) - max(kpc_ac_energy_yield_wh_total offset $resolution)",
     "legendFormat": "PV"
    },
    {
     "expr": "max(kpc_ac_energy_to_grid_wh_total) - max(kpc_ac_energy_to_grid_wh_total offset $resolution)",
     "legendFormat": "To Grid"
    }
   ]
  },
  {
   "title": "Car Charging",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "increase(max(pvcontrol:total_charged_energy_wh_total)[$resolution:])",
     "legendFormat": "Car"
    },
    {
     "expr": "increase(max(pvcontrol:charged_energy_wh_total{source=\"grid\"})[$resolution:])",
     "legendFormat": "Grid"
    }
   ]
  },
  {
   "title": "Nibe Heatpump",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "increase(max(nibe_energy_meter_wh_total)[$resolution:])",
     "legendFormat": "Nibe"
    },
    {
     "expr": "increase(max(source:nibe_energy_meter_wh_total{source=\"grid\"})[$resolution:])",
     "legendFormat": "Grid"
    }
   ]
  }
 ]
}