apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbus-exporter
spec:
  selector:
    matchLabels:
      app: modbus-exporter
  replicas: 2
  template:
    metadata:
      labels:
        app: modbus-exporter
    spec:
      containers:
        - name: modbus-exporter
          image: stephanme/modbus_exporter:v5
          ports:
            - containerPort: 9602
          command:
            - ./modbus_exporter
            - --config.file
            - /app/config/modbus.yml
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: modbus-exporter-config
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: modbus-exporter
          matchLabelKeys:
            - pod-template-hash
---
# requires k8s 1.21
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: modbus-exporter
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: modbus-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: modbus-exporter
  labels:
    app: modbus-exporter
spec:
  ports:
    - port: 9602
      targetPort: 9602
      name: tcp
  selector:
    app: modbus-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: modbus-exporter
spec:
  endpoints:
  - path: /metrics
    port: tcp
  - path: /modbus
    port: tcp
    params:
      target: ["scb.fritz.box:1502"]
      module: ["kostal-inverter"]
      sub_target: ["71"] # Modbus unit identifier
    relabelings:
      - action: replace
        replacement: modbus-exporter-kostal-inverter
        targetLabel: job
      - action: replace
        sourceLabels: [__param_target]
        targetLabel: instance
      - action: labeldrop
        regex: pod
  - path: /modbus
    port: tcp
    params:
      target: ["go-echarger.fritz.box:502"]
      module: ["go-e-wallbox"]
      sub_target: ["1"] # Modbus unit identifier
    relabelings:
    - action: replace
      replacement: modbus-exporter-go-e-wallbox
      targetLabel: job
    - action: replace
      sourceLabels: [__param_target]
      targetLabel: instance
    - action: labeldrop
      regex: pod
  selector:
    matchLabels:
      app: modbus-exporter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modbus-exporter-config
data:
  modbus.yml: |-
    modules:
      # Module name, needs to be passed as parameter by Prometheus.
      - name: "kostal-inverter"
        protocol: 'tcp/ip'
        metrics:
          - name: "kpc_dc_power_total_watts"
            help: "Total DC power"
            address: 300100
            dataType: float32
            metricType: gauge
          - name: "kpc_dc_power_watts"
            help: "DC power"
            labels:
              source: "DC1"
            address: 300260
            dataType: float32
            metricType: gauge
          - name: "kpc_dc_power_watts"
            labels:
              source: "DC2"
            address: 300270
            dataType: float32
            metricType: gauge
          - name: "kpc_dc_power_watts"
            labels:
              source: "DC3"
            address: 300280
            dataType: float32
            metricType: gauge

          - name: "kpc_home_power_consumption_wh_total"
            help: "Total home consumption"
            labels:
              source: "battery"
            address: 300110
            dataType: float32
            metricType: counter
          - name: "kpc_home_power_consumption_wh_total"
            labels:
              source: "grid"
            address: 300112
            dataType: float32
            metricType: counter
          - name: "kpc_home_power_consumption_wh_total"
            labels:
              source: "pv"
            address: 300114
            dataType: float32
            metricType: counter
          - name: "kpc_home_power_consumption_total_wh_total"
            address: 300118
            dataType: float32
            metricType: counter

          - name: "kpc_home_power_consumption_watts"
            help: "Current home consumption"
            labels:
              source: "battery"
            address: 300106
            dataType: float32
            metricType: gauge
          - name: "kpc_home_power_consumption_watts"
            labels:
              source: "grid"
            address: 300108
            dataType: float32
            metricType: gauge
          - name: "kpc_home_power_consumption_watts"
            labels:
              source: "pv"
            address: 300116
            dataType: float32
            metricType: gauge

          - name: "kpc_ac_power_total_watts"
            help: "Total AC active power"
            address: 300172
            dataType: float32
            metricType: gauge
          - name: "kpc_ac_power_watts"
            help: "AC active power"
            labels:
              source: "L1"
            address: 300156
            dataType: float32
            metricType: gauge
          - name: "kpc_ac_power_watts"
            help: "AC active power"
            labels:
              source: "L2"
            address: 300162
            dataType: float32
            metricType: gauge
          - name: "kpc_ac_power_watts"
            help: "AC active power"
            labels:
              source: "L3"
            address: 300168
            dataType: float32
            metricType: gauge

          - name: "kpc_powermeter_total_watts"
            help: "Total active power (powermeter)"
            address: 300252
            dataType: float32
            metricType: gauge
          - name: "kpc_powermeter_watts"
            help: "Active power (powermeter)"
            labels:
              source: "L1"
            address: 300224
            dataType: float32
            metricType: gauge
          - name: "kpc_powermeter_watts"
            help: "Active power (powermeter)"
            labels:
              source: "L2"
            address: 300234
            dataType: float32
            metricType: gauge
          - name: "kpc_powermeter_watts"
            help: "Active power (powermeter)"
            labels:
              source: "L3"
            address: 300244
            dataType: float32
            metricType: gauge

          - name: "kpc_dc_energy_wh_total"
            labels:
              source: "dc1"
            address: 301058
            dataType: float32
            metricType: counter
          - name: "kpc_dc_energy_wh_total"
            labels:
              source: "dc2"
            address: 301060
            dataType: float32
            metricType: counter
          - name: "kpc_dc_energy_wh_total"
            labels:
              source: "dc3"
            address: 301062
            dataType: float32
            metricType: counter
          - name: "kpc_dc_energy_total_wh_total"
            address: 301056
            dataType: float32
            metricType: counter

          - name: "kpc_ac_energy_yield_wh_total"
            help: "AC energy total yield"
            address: 300320
            dataType: float32
            metricType: counter

          - name: "kpc_ac_energy_to_grid_wh_total"
            address: 301064
            dataType: float32
            metricType: counter

      - name: "go-e-wallbox"
        protocol: 'tcp/ip'
        metrics:
          - name: "goe_car_state"
            address: 400100
            dataType: uint16
            metricType: gauge
          - name: "goe_error"
            address: 400101
            dataType: uint16
            metricType: gauge

          - name: "goe_voltage_volts"
            labels:
              source: "L1"
            address: 400108
            dataType: uint32
            endianness: yolo
            metricType: gauge
          - name: "goe_voltage_volts"
            labels:
              source: "L2"
            address: 400110
            dataType: uint32
            endianness: yolo
            metricType: gauge
          - name: "goe_voltage_volts"
            labels:
              source: "L3"
            address: 400112
            dataType: uint32
            endianness: yolo
            metricType: gauge
          - name: "goe_voltage_volts"
            labels:
              source: "N"
            address: 400144
            dataType: uint32
            endianness: yolo
            metricType: gauge

          - name: "goe_current_amperes"
            labels:
              source: "L1"
            address: 400114
            dataType: uint32
            endianness: yolo
            metricType: gauge
            factor: 0.1
          - name: "goe_current_amperes"
            labels:
              source: "L2"
            address: 400116
            dataType: uint32
            endianness: yolo
            metricType: gauge
            factor: 0.1
          - name: "goe_current_amperes"
            labels:
              source: "L3"
            address: 400118
            dataType: uint32
            endianness: yolo
            metricType: gauge
            factor: 0.1

          - name: "goe_power_total_watts"
            address: 400120
            dataType: uint32
            endianness: yolo
            metricType: gauge
            factor: 10
          - name: "goe_energy_wh_total"
            address: 400128
            dataType: uint32
            endianness: yolo
            metricType: counter
            factor: 100
          - name: "goe_charged_energy_wh"
            address: 400132
            dataType: uint32
            endianness: yolo
            metricType: counter
            factor: 0.00277778

          - name: "goe_power_watts"
            labels:
              source: "L1"
            address: 400146
            dataType: uint32
            endianness: yolo
            metricType: gauge
            factor: 100
          - name: "goe_power_watts"
            labels:
              source: "L2"
            address: 400148
            dataType: uint32
            endianness: yolo
            metricType: gauge
            factor: 100
          - name: "goe_power_watts"
            labels:
              source: "L3"
            address: 400150
            dataType: uint32
            endianness: yolo
            metricType: gauge
            factor: 100

          - name: "goe_allow_charging"
            address: 300200
            dataType: uint16
            metricType: gauge
          - name: "goe_phases"
            address: 400205
            dataType: uint16
            metricType: gauge
          - name: "goe_max_current_amperes"
            address: 300299
            dataType: uint16
            metricType: gauge
