{
 "title": "Wallbox",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Charge Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max(goe_power_total_watts) without(pod, instance)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "max(goe_max_current_amperes) without (pod,instance)",
     "legendFormat": "Max"
    },
    {
     "expr": "max(goe_current_amperes) without (pod, instance)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Phases",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max( floor(goe_phases / 32) % 2  + floor(goe_phases / 16) % 2 + floor(goe_phases / 8) % 2) without (pod,instance)",
     "legendFormat": "In"
    },
    {
     "expr": "max( floor(goe_phases / 4) % 2  + floor(goe_phases / 2) % 2 + goe_phases % 2) without (pod,instance)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Allow Charging",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(goe_allow_charging) without(pod,instance)"
    }
   ]
  },
  {
   "title": "Car State",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(goe_car_state) without (pod, instance)",
     "legendFormat": " "
    }
   ]
  }
 ]
}